version: "3.9"
services:

  # Database Postgres
  db:
    image: postgres:14-alpine3.18
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_sft
    ports:
      - ${POSTGRES_PORT:-15437}:5432
    container_name: test_sft_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test_sft" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  # Django App
  web:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.local
    volumes:
      - ./:/test_sft
      - ./logs:/test_sft/logs/
      - ./src/static:/test_sft/src/static/
      - ./src/media:/test_sft/src/media/
    ports:
      - 8031:8000
    links:
      - db
    image: app:django
    container_name: test_sft_web
    command: >
      sh -c "./docker/wait-for-it.sh db:5432 -- sh ./docker/backend/entrypoint-web.sh"
    depends_on:
      db:
        condition: service_healthy
