# Generated by Django 5.0.2 on 2024-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='disable_flag_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='disable_flag_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='enable_flag_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='enable_flag_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
    ]
