# Generated by Django 5.0.2 on 2024-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_disable_flag_1_customer_disable_flag_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='disable_flag_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='disable_flag_2',
            field=models.BooleanField(default=False),
        ),
    ]
